MenuP="""
AGENCIA DE REMISES

MENU PRINCIPAL

1 - GESTIONAR AUTOS
2 - GESTIONAR CLIENTES
3 - GESTIONAR RESERVAS
4 - Salir
"""

def MenuPrincipal():
    print(MenuP)


MenuA="""
MENU PRINCIPAL / AUTOS

1 - INGRESAR NUEVO AUTO
2 - MODIFICAR CHOFER
3 - MOSTRAR AUTOS DISPONIBLES
4 - MOSTRAR TODOS LOS AUTOS
5 - BUSCAR AUTO
6 - VOLVER AL MENU ANTERIOR
"""

def MenuAutos():
    print(MenuA)


MenuC="""
MENU PRINCIPAL / CLIENTES

1 - INGRESAR NUEVO CLIENTE
2 - DESHABILITAR CLIENTE
3 - HABILITAR CLIENTE
4 - MOSTRAR CLIENTES
5 - BUSCAR CLIENTE
6 - VOLVER AL MENU ANTERIOR
"""

def MenuClientes():
    print(MenuC)


SubMenuC="""
MENU PRINCIPAL / CLIENTES / BUSCAR CLIENTE

1 - BUSCAR POR ID
2 - BUSCAR POR TELEFONO
3 - VOLVER AL MENU ANTERIOR
"""

def MenuClientesBuscar():
    print(SubMenuC)

SubMenuC2="""
MENU PRINCIPAL / CLIENTES / MODIFICAR ESTADO DEL CLIENTE

1 - HABILITAR
2 - DESHABILITAR
3 - CANCELAR
"""

def MenuClientesEstado():
    print(SubMenuC2)


MenuR="""
MENU PRINCIPAL / RESERVAS

1 - INGRESAR NUEVA RESERVA
2 - CAMBIAR ESTADO DE RESERVA
3 - MOSTRAR RESERVAS CONFIRMADAS
4 - MOSTRAR RESERVAS CANCELADAS
5 - MOSTRAR TODAS LAS RESERVAS
6 - BUSCAR RESERVA
7 - VOLVER AL MENU ANTERIOR
"""

def MenuReservas():
    print(MenuR)

SubMenuR="""
MENU PRINCIPAL / RESERVAS / INGRESAR NUEVA RESERVA

1 - CONSULTAR AUTOS DISPONIBLES (RESERVA PARA AHORA)
2 - REGISTRAR RESERVA
3 - REGISTRAR RESERVA PARA OTRO MOMENTO
4 - VOLVER AL MENU ANTERIOR
"""

def SubMenuReservas():
    print(SubMenuR)

SubMenuR2="""
MENU PRINCIPAL / RESERVAS / CAMBIAR ESTADO DE RESERVA

1 - CONFIRMAR RESERVA
2 - CANCELAR RESERVA
3 - CANCELAR
"""

def MenurReservaEstado():
    print(SubMenuR2)

SubMenuR3="""
MENU PRINCIPAL / RESERVAS / BUSCAR RESERVAS

1 - BUSCAR POR ID
2 - BUSCAR POR PATENTE DE AUTO ASIGNADO
3 - BUSCAR POR ID DE CLIENTE
4 - VOLVER AL MENU ANTERIOR
"""

def MenuReservasBuscar():
    print(SubMenuR3)